import type { Metadata } from "next";
import {Navigation} from "@/components/navigation";
import 'material-icons/iconfont/material-icons.css';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div id="wrapper" className="container mx-auto h-screen">
          <Navigation/>
          {children}
      </div>
      </body>
    </html>
  );
}
