# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(frontend|docker)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, css, scss, javascript, json]
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1 # Use the latest version
    hooks:
      - id: djlint-reformat-jinja
        types_or: ["html", "jinja"]
      - id: djlint-jinja
        types_or: ["html", "jinja"]
        # Optional: Add additional arguments
        args: ["--reformat"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        exclude: '.*\.html$'
      # Run the formatter
      - id: ruff-format
        exclude: '.*\.html$'
