services:
  backend:
    restart: on-failure
    build:
      context: backend
    image: pointsheet:latest
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/auth.json
    ports:
      - "5000"
    volumes:
      - ./backend/pointsheet:/app
    env_file:
      - backend/pointsheet/.env

  background_tasks:
    image: pointsheet:latest
    extends:
      service: backend
    depends_on:
      - backend
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/auth.json
    command: |
      celery -A pointsheet.celery_worker worker --loglevel=info

  nginx_proxy:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/pointsheet.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/pointsheet/static:/app/static
    depends_on:
      - backend
    extra_hosts:
      - "pointsheet-app.com:127.0.0.1"
      - "api.pointsheet-app.com:127.0.0.1"

volumes:
  node_modules:
  frontend_static:
