services:
  backend:
    restart: on-failure
    build:
      context: backend
    container_name: pointsheet-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend/pointsheet:/app

  frontend:
    restart: on-failure
    build:
      context: frontend
    container_name: pointsheet
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app