services:
  backend:
    build:
      context: backend
    container_name: pointsheet-api
    ports:
      - "5000"
    volumes:
      - ./backend/pointsheet:/app

  frontend:
    restart: on-failure
    build:
      context: frontend
    container_name: pointsheet
    ports:
      - "3000"
    volumes:
      - ./frontend:/app

  nginx_proxy:
    image: nginx:1.20-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/pointsheet.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
