services:
  backend:
    restart: on-failure
    build:
      context: backend
    image: pointsheet:latest
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/auth.json
    ports:
      - "5000"
    volumes:
      - ./backend/pointsheet:/app
    env_file:
      - backend/pointsheet/.env

  background_tasks:
    image: pointsheet:latest
    extends:
      service: backend
    depends_on:
      - backend
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/auth.json
    command: |
      celery -A pointsheet.celery_worker worker --loglevel=info

  frontend:
    restart: on-failure
    build:
      context: frontend
    container_name: frontend
    working_dir: /app
    command: npm run dev
    ports:
      - "5173"
    volumes:
      - ./frontend:/app/
      - node_modules:/app/node_modules

  nginx_proxy:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/pointsheet.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  node_modules:
