"""series_event_relationship

Revision ID: f483acbcee7d
Revises: 6658fdde2841
Create Date: 2024-12-18 23:39:23.020950

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f483acbcee7d"
down_revision: Union[str, None] = "6658fdde2841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "series_event", "series", ["series"], ["id"], ondelete="cascade"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("series_event", type_="foreignkey")

    # ### end Alembic commands ###
