"""new

Revision ID: abc05ea6c9a2
Revises: 
Create Date: 2024-12-13 00:26:43.412078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = 'abc05ea6c9a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', pointsheet.models.custom_types.SeriesStatusType, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    op.drop_table('events')
    # ### end Alembic commands ###
