"""init

Revision ID: 8afcee10567b
Revises:
Create Date: 2024-12-13 21:22:40.620272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "8afcee10567b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "series",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "status", pointsheet.models.custom_types.SeriesStatusType, nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("series")
    op.drop_table("events")
    # ### end Alembic commands ###
