"""add_status_to_event_model

Revision ID: 19f944c50784
Revises: 7fdcb587117d
Create Date: 2024-12-23 14:30:46.751044

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import pointsheet

# revision identifiers, used by Alembic.
revision: str = "19f944c50784"
down_revision: Union[str, None] = "7fdcb587117d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status", pointsheet.models.custom_types.EventStatusType, nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
