"""make_series_status_nullable

Revision ID: 508cd65d146f
Revises: 63f6588459b2
Create Date: 2024-12-19 00:04:31.910141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "508cd65d146f"
down_revision: Union[str, None] = "63f6588459b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.alter_column("status", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
