"""add_start_end_date

Revision ID: f722dcd3caf2
Revises: 508cd65d146f
Create Date: 2024-12-20 20:12:24.598652

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import pointsheet

# revision identifiers, used by Alembic.
revision: str = "f722dcd3caf2"
down_revision: Union[str, None] = "508cd65d146f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("starts_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("ends_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "host", pointsheet.models.custom_types.EntityIdType, nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("host")
        batch_op.drop_column("ends_at")
        batch_op.drop_column("starts_at")

    # ### end Alembic commands ###
