"""series_event_relationship

Revision ID: 6658fdde2841
Revises: 8afcee10567b
Create Date: 2024-12-18 23:30:42.730636

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6658fdde2841"
down_revision: Union[str, None] = "8afcee10567b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
