"""initial models

Revision ID: 7fdcb587117d
Revises:
Create Date: 2024-12-22 16:41:30.522659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import pointsheet

# revision identifiers, used by Alembic.
revision: str = "7fdcb587117d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "series",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "status", pointsheet.models.custom_types.SeriesStatusType, nullable=True
        ),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("series", pointsheet.models.custom_types.EntityIdType, nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("host", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.ForeignKeyConstraint(
            ["series"], ["series.id"], name="series_event", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    op.drop_table("series")
    # ### end Alembic commands ###
