"""series_start_end_date

Revision ID: 63f6588459b2
Revises: f483acbcee7d
Create Date: 2024-12-18 23:47:26.039634

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63f6588459b2"
down_revision: Union[str, None] = "f483acbcee7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.add_column(sa.Column("starts_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("ends_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_column("ends_at")
        batch_op.drop_column("starts_at")

    # ### end Alembic commands ###
