"""add game id to event

Revision ID: 06372d58cd77
Revises: cd325168aea2
Create Date: 2025-06-21 22:15:02.535019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06372d58cd77'
down_revision: Union[str, None] = 'cd325168aea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('event_game', 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('event_game', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
