"""add_event_to_driver

Revision ID: 506377a26b31
Revises: 60a6c9ce278d
Create Date: 2025-01-20 21:44:10.843897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "506377a26b31"
down_revision: Union[str, None] = "60a6c9ce278d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drivers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "event", pointsheet.models.custom_types.EntityIdType, nullable=False
            )
        )
        batch_op.drop_constraint("drivers_event", type_="foreignkey")
        batch_op.create_foreign_key(
            "drivers_event", "events", ["event"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("event_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drivers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.CHAR(), nullable=False))
        batch_op.drop_constraint("drivers_event", type_="foreignkey")
        batch_op.create_foreign_key(
            "drivers_event", "events", ["event_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("event")

    # ### end Alembic commands ###
