"""rename event.Drivers to Participants

Revision ID: 3cf5d64cf49b
Revises: d99fec20e928
Create Date: 2025-05-23 09:51:57.837011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "3cf5d64cf49b"
down_revision: Union[str, None] = "d99fec20e928"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "team_id", pointsheet.models.custom_types.EntityIdType, nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participants",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "event_id", pointsheet.models.custom_types.EntityIdType, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="drivers_event", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "event_id", name="unique_driver_event"),
    )
    op.drop_table("users")
    op.drop_table("event_drivers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_drivers",
        sa.Column("id", sa.CHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("event_id", sa.CHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="drivers_event", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "event_id", name="unique_driver_event"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.CHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("team_id", sa.CHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("participants")
    op.drop_table("drivers")
    # ### end Alembic commands ###
