"""rename event_shedules_to_schedule

Revision ID: 85b01585fbc5
Revises: d96cec92f516
Create Date: 2025-01-14 17:02:00.785870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85b01585fbc5"
down_revision: Union[str, None] = "d96cec92f516"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_schedule", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
