"""add cover image to series

Revision ID: 220dd447150d
Revises: 3cf5d64cf49b
Create Date: 2025-05-24 21:59:09.789935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "220dd447150d"
down_revision: Union[str, None] = "3cf5d64cf49b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cover_image", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_column("cover_image")

    # ### end Alembic commands ###
