"""add description field

Revision ID: 8bb9245577db
Revises: 220dd447150d
Create Date: 2025-05-25 22:09:42.066978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bb9245577db"
down_revision: Union[str, None] = "220dd447150d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("series", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
