"""create_driver_model

Revision ID: 3a6c904ac286
Revises: 858b0a02dcb8
Create Date: 2025-01-12 23:43:08.568578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "3a6c904ac286"
down_revision: Union[str, None] = "858b0a02dcb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("driver")
    # ### end Alembic commands ###
