"""schedule_pk_to_int

Revision ID: e7c5a3d21973
Revises: 85b01585fbc5
Create Date: 2025-01-14 17:14:03.235115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7c5a3d21973"
down_revision: Union[str, None] = "85b01585fbc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_schedule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nbr_of_laps", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("duration", sa.String(length=255), nullable=True))
        batch_op.alter_column(
            "id",
            existing_type=sa.CHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_schedule", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.CHAR(),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.drop_column("duration")
        batch_op.drop_column("nbr_of_laps")

    # ### end Alembic commands ###
