"""add team

Revision ID: d99fec20e928
Revises: 9351cf49f846
Create Date: 2025-05-23 07:29:22.846179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "d99fec20e928"
down_revision: Union[str, None] = "9351cf49f846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "owner_id", pointsheet.models.custom_types.EntityIdType, nullable=False
        ),
        sa.Column("members", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "team_id", pointsheet.models.custom_types.EntityIdType, nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("drivers")
    with op.batch_alter_table("event_schedule", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    with op.batch_alter_table("race_results", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("race_results", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("event_schedule", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    op.create_table(
        "drivers",
        sa.Column("id", sa.CHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("users")
    op.drop_table("teams")
    # ### end Alembic commands ###
