"""add webhook models

Revision ID: bb6b548efbcf
Revises: 5e5fd47d32ba
Create Date: 2025-07-04 08:04:15.754310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = 'bb6b548efbcf'
down_revision: Union[str, None] = '5e5fd47d32ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_subscriptions',
    sa.Column('id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('webhook_id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', pointsheet.models.custom_types.EntityIdType, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_logs',
    sa.Column('id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('webhook_id', pointsheet.models.custom_types.EntityIdType, nullable=False),
    sa.Column('subscription_id', pointsheet.models.custom_types.EntityIdType, nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_logs')
    op.drop_table('webhook_subscriptions')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
