"""track_length_as_string

Revision ID: 9351cf49f846
Revises: ff0573878823
Create Date: 2025-04-20 21:54:20.430663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9351cf49f846"
down_revision: Union[str, None] = "ff0573878823"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.alter_column(
            "length",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.alter_column(
            "length",
            existing_type=sa.String(length=20),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
