"""add game table

Revision ID: add_game_table
Revises: 6c0a3adc19fa
Create Date: 2025-06-02 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = 'add_game_table'
down_revision: Union[str, None] = '6c0a3adc19fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create games table
    op.create_table('games',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    # Add game_id column to cars table
    op.add_column('cars', sa.Column('game_id', sa.Integer(), nullable=True))
    
    # Create foreign key from cars.game_id to games.id
    op.create_foreign_key(
        'fk_cars_games', 'cars', 'games',
        ['game_id'], ['id']
    )
    
    # Create a default game for existing cars
    op.execute("""
        INSERT INTO games (name) 
        SELECT DISTINCT game FROM cars
    """)
    
    # Update cars.game_id based on games.name matching cars.game
    op.execute("""
        UPDATE cars
        SET game_id = (
            SELECT id FROM games WHERE name = cars.game
        )
    """)
    
    # Make game_id not nullable
    op.alter_column('cars', 'game_id', nullable=False)
    
    # Drop the old game column
    op.drop_column('cars', 'game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the game column
    op.add_column('cars', sa.Column('game', sa.String(length=255), nullable=True))
    
    # Update cars.game based on games.name
    op.execute("""
        UPDATE cars
        SET game = (
            SELECT name FROM games WHERE id = cars.game_id
        )
    """)
    
    # Make game not nullable
    op.alter_column('cars', 'game', nullable=False)
    
    # Drop the foreign key and game_id column
    op.drop_constraint('fk_cars_games', 'cars', type_='foreignkey')
    op.drop_column('cars', 'game_id')
    
    # Drop the games table
    op.drop_table('games')
    # ### end Alembic commands ###