"""add_registered_on

Revision ID: 858b0a02dcb8
Revises: bdd4bf05df36
Create Date: 2025-01-12 11:02:00.846309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "858b0a02dcb8"
down_revision: Union[str, None] = "bdd4bf05df36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("registered_on", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_column("registered_on")

    # ### end Alembic commands ###
