"""rename_drivers_tables

Revision ID: 57a18fa2e1e6
Revises: 346530d1c883
Create Date: 2025-01-21 23:20:11.228465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "57a18fa2e1e6"
down_revision: Union[str, None] = "346530d1c883"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_drivers",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "event_id", pointsheet.models.custom_types.EntityIdType, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="drivers_event", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("driver")
    with op.batch_alter_table("drivers", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.drop_constraint("drivers_event", type_="foreignkey")
        batch_op.drop_column("event_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drivers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.CHAR(), nullable=False))
        batch_op.create_foreign_key(
            "drivers_event", "events", ["event_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    op.create_table(
        "driver",
        sa.Column("id", sa.CHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("event_drivers")
    # ### end Alembic commands ###
