"""update-password-to-hash

Revision ID: 346530d1c883
Revises: 506377a26b31
Create Date: 2025-01-21 21:45:42.824315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "346530d1c883"
down_revision: Union[str, None] = "506377a26b31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drivers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "event_id", pointsheet.models.custom_types.EntityIdType, nullable=False
            )
        )
        batch_op.drop_constraint("drivers_event", type_="foreignkey")
        batch_op.create_foreign_key(
            "drivers_event", "events", ["event_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("event")

    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.Text(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )

    with op.batch_alter_table("drivers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event", sa.CHAR(), nullable=False))
        batch_op.drop_constraint("drivers_event", type_="foreignkey")
        batch_op.create_foreign_key(
            "drivers_event", "events", ["event"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("event_id")

    # ### end Alembic commands ###
