"""add_schedule_to_event

Revision ID: d96cec92f516
Revises: 3a6c904ac286
Create Date: 2025-01-14 16:51:26.883030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pointsheet

# revision identifiers, used by Alembic.
revision: str = "d96cec92f516"
down_revision: Union[str, None] = "3a6c904ac286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_schedule",
        sa.Column("id", pointsheet.models.custom_types.EntityIdType, nullable=False),
        sa.Column(
            "event_id", pointsheet.models.custom_types.EntityIdType, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name="event_schedule_event", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_schedule")
    # ### end Alembic commands ###
