"""unique-constraints-driver_event

Revision ID: 6c7e97872809
Revises: 57a18fa2e1e6
Create Date: 2025-02-04 17:28:43.395984

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6c7e97872809"
down_revision: Union[str, None] = "57a18fa2e1e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_drivers", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_driver_event", ["id", "event_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_drivers", schema=None) as batch_op:
        batch_op.drop_constraint("unique_driver_event", type_="unique")

    # ### end Alembic commands ###
